import type { Metadata } from "next";

import { createPreviewLinkURL } from "./utils";

const METADATA_TITLE = "Yadhst";
const METADATA_DESCRIPTION =
    "Hi I'm Fayyadh Abdurrohman, I'm a web developer passionate about developing and coding. This portfolio showcases my projects, skills, and experience in web development and another things.";
const METADATA_COVER = createPreviewLinkURL(
    "https://yadh.vercel.app/",
    1200,
    630
);
const METADATA_MEDIA_IMAGE = {
    url: METADATA_COVER,
    width: 1200,
    height: 630,
    alt: "Website Preview Generated by microlink.io",
};

type MetadataData = Metadata & { title: string; description: string };
export const METADATA: MetadataData = {
    title: METADATA_TITLE,
    description: METADATA_DESCRIPTION,
    authors: [{ name: "Yadhst", url: "https://github.com/yadhst" }],
    keywords: [
        "portfolio",
        "personal",
        "web developer",
        "web design",
        "frontend",
        "next.js",
        "javascript",
        "react",
        "tailwindcss",
    ],
    icons: {
        icon: "https://fav.farm/🔥",
        apple: "https://fav.farm/🔥",
    },
    openGraph: {
        title: METADATA_TITLE,
        description: METADATA_DESCRIPTION,
        url: "https://yadh.vercel.app/",
        siteName: METADATA_TITLE,
        images: [METADATA_MEDIA_IMAGE],
        locale: "en_US",
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: METADATA_TITLE,
        description: METADATA_DESCRIPTION,
        site: METADATA_TITLE,
        images: [METADATA_MEDIA_IMAGE],
    },
};
